import enum


class SettingCode(enum.Enum):
    CHANGE_GROUP = "CHANGE_GROUP"
    NEW_SCHEDULE_NOTIFICATION = "NEW_SCHEDULE_NOTIFICATION"
    CHANGED_SCHEDULE_NOTIFICATION = "CHANGED_SCHEDULE_NOTIFICATION"
    COMING_LESSONS_NOTIFICATION = "COMING_LESSONS_NOTIFICATION"