name: Bot CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Bot deploying
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /projects/HsePermHelperBot
            git pull
            docker-compose build
            docker-compose up -d
